### ISSUE TITLE
`process_hms` refactoring: treat all levels at once

### ISSUE THREAD

**Issue by sigmafelix** [NIEHS/amadeus#101]
The current `process_hms` takes `variable` argument to return each variable's aggregated polygons. As introduced today's meeting, when overlapping polygons with different levels exist, a certain point location would have 1s across different level fields (`light_0`, `medium_0`, `heavy_0`). I propose to take all levels into account in `process_hms`. I think that potential changes will not require manuscript editing since we did not include this detail in it. I'd be working on refactoring as it is closely related to `beethoven` work and needs to be resolved as soon as possible.

Would this work for you @mitchellmanware ?

**Comment by mitchellmanware** [comment]
Yes, that makes sense and is a good change to the function. Let me know if/how i can help this update.

**Comment by sigmafelix** [comment]
Thanks. I will ping you when I have a refactored function and its tests.

**Comment by sigmafelix** [comment]
https://github.com/NIEHS/amadeus/commit/b071841dedd6ccbcb409b614807cd7d1fc380c93
