### ISSUE TITLE
functions exposed to the cran user manual

### ISSUE THREAD

**Issue by kyle-messier** [NIEHS/amadeus#123]
We should consider changes in the functions exposed that get printed/included in the [cran user manual](https://cran.r-project.org/web/packages/amadeus/amadeus.pdf)

**Comment by mitchellmanware** [comment]
I think the `@keywords internal` tag was not included for some of the newer auxiliary functions. Adding this tag makes the functions available but does not include them in the documentation, example here with `download_setup_dir`.
<img width="1512" alt="Screenshot 2024-09-03 at 7 00 05 AM" src="https://github.com/user-attachments/assets/3ff51d44-4fa5-4fa4-92cc-8a5776eaafc1">
