### ISSUE TITLE
1.1.0 checklist

### ISSUE THREAD

**Issue by kyle-messier** [NIEHS/amadeus#125]
- [x] README - reduce installation options to CRAN and `pak`
  - https://github.com/NIEHS/amadeus/commit/5d290497ee2df456803273ebccb73fc920da7a52
- [x] #123 
  - https://github.com/NIEHS/amadeus/commit/b96bb64faee3fd940e1c12b1669189e3a2bd3ba6

**Comment by mitchellmanware** [comment]
@kyle-messier @eva0marques @eva0marques 

Going forward I think we should only submit new versions to CRAN for major (ie. 1.0.0 -> 2.0.0) and minor (ie 1.0.0 -> 1.1.0) changes, not for small patches. Patching the main branch of GitHub repository is good for tracking fixes and documenting version progression, but based on the [CRAN re-submission policy](https://cran.r-project.org/web/packages/policies.html#Re_002dsubmission-1) we should be submitting formal updates "no more than every 1–2 months".

I think we will get some real bugs and important patches as the package is used more, so 1.1.0 will probably be upon us soon.

**Comment by kyle-messier** [comment]
@mitchellmanware That is reasonable. I'll update the issue name

**Comment by mitchellmanware** [comment]
As we are now passed `1.1.0`, I have migrated the previously incomplete tasks to the 1.1.4 checklist (https://github.com/NIEHS/amadeus/issues/134)
