### ISSUE TITLE
add optional hash as `download_*` output

### ISSUE THREAD

**Issue by kyle-messier** [NIEHS/amadeus#127]
For `target` pipelines it is often helpful to have a `return()` value to track. We can simply add an optional input that creates a hash file to track. 

`hash = FALSE`: current behavior 
`hash = TRUE` : returns a hash value. 

We already have `rlang` as an import, so we can use `rlang::hash()` or `rlang::hash_file()` 
https://rlang.r-lib.org/reference/hash.html

**Comment by mitchellmanware** [comment]
https://github.com/NIEHS/amadeus/pull/128
