### ISSUE TITLE
coverage report via GH-actions

### ISSUE THREAD

**Issue by kyle-messier** [NIEHS/amadeus#42]
@sigmafelix @mitchellmanware  Given that the NIEHS org won't allow codecov.io 3-rd party integration for our coverage analysis and badge, I've tried a straight up GitHub action only solution. Unfortunately, I (and ChatGPT, CoPilot) have not been successful. 

Here is the relevant repo **https://github.com/marketplace/actions/create-coverage-badges**

Lower priority than other Amadeus tasks, but if y'all want to give it a try, that would be great. 

Again, the idea is that we want to call covr as normal in the workflow, but instead of sending the report to codecov.io, we retain the report, [create a badge ](https://shields.io/)based off that report, and update the README.md

**Comment by sigmafelix** [comment]
@kyle-messier @mitchellmanware Working on it. Still finding errors but made some progress. I will try to figure it out soon.

**Comment by mitchellmanware** [comment]
I was trying as well but had issues with one of the `download_epa_certificate()` unit tests. I stopped working on it for today but I will continue tomorrow if not complete.

@kyle-messier @sigmafelix

**Comment by sigmafelix** [comment]
@kyle-messier 
I succeed to put a svg badge in my own repository (https://github.com/sigmafelix/speed/blob/main/.github/workflows/coverage-local.yml). In #43, it failed since GA appears to have no writing privilege. Could you check if it is active? (cf. https://github.com/we-cli/coverage-badge-action)

**Comment by kyle-messier** [comment]
@sigmafelix That's great! Is GA the GitHub Action? As in, the action needs write privilege to `main`?

**Comment by sigmafelix** [comment]
@kyle-messier Yes, it is GitHub Action. Could you find if Settings -> Action -> General -> Workflow permissions choose Read and Write permissions is selected?

**Comment by kyle-messier** [comment]
@sigmafelix Ok, updated and re-running.

**Comment by sigmafelix** [comment]
Closing this issue as changes in #43 were pulled.

**Comment by sigmafelix** [comment]
A local badge generation relies on the GitHub user webpage in github.io domain. We need to check if we can write to NIEHS.github.io.

Cf:

https://github.com/NIEHS/amadeus/blob/97039d9f2473b56404b5e0879fcb947ae56458f5/.github/workflows/test-coverage-local.yaml#L52-L55

https://github.com/NIEHS/amadeus/blob/97039d9f2473b56404b5e0879fcb947ae56458f5/README.md?plain=1#L4

**Comment by sigmafelix** [comment]
Looks like it worked without any errors. I will close the issue.
