### ISSUE TITLE
`download_*_data` function names

### ISSUE THREAD

**Issue by mitchellmanware** [NIEHS/amadeus#66]
Should we remove "_data" from all the source-specific download functions. Ie `download_geos_data` -> `download_geos`. Currently the processing and covariate functions use similar pattern (`process_geos` and `calc_geos`).

@sigmafelix @kyle-messier @eva0marques

**Comment by kyle-messier** [comment]
@mitchellmanware consistency is always good. If there is no other option after the data source such as `download_geos_data` and `download_geos_X`, then I'd say to simplify and make consistent. Thanks!

**Comment by mitchellmanware** [comment]
See commit 9c2502afb3037ecb0375ec4697e699d87601e393
