### ISSUE TITLE
Retain columns in `calc_covariates`

### ISSUE THREAD

**Issue by mitchellmanware** [NIEHS/amadeus#69]
Currently, `calc_worker` limits output to the `locs_id`, `time`, `levels`, and data value columns. It does not return the other columns from `locs`.

Add `retain_columns` (or similar name) to allow user to retain all data from `locs`.

**Comment by mitchellmanware** [comment]
I also wanted to limit the number of columns in the output for easier interpretation, but I agree including the geometries with the "locs_id" is essential information.

**Comment by mitchellmanware** [comment]
@sigmafelix
Default will be `FALSE` and i have included a note for long geometry strings associated with polygon features.

**Comment by sigmafelix** [comment]
@mitchellmanware Sounds great, thank you!
