### ISSUE TITLE
update README.md

### ISSUE THREAD

**Issue by mitchellmanware** [NIEHS/amadeus#72]
- [x] How to install via GitHub
- [x] Examples to reflect new function names and output
- [x] New data sources in table
- [x] Citations

**Comment by kyle-messier** [comment]
- [ ] Update stale vignettes (epa data download is the version before amadeus)

**Comment by mitchellmanware** [comment]
updating stale vignettes opened in new issue https://github.com/NIEHS/amadeus/issues/96
