### ISSUE TITLE
Refactoring

### ISSUE THREAD

**Issue by sigmafelix** [NIEHS/amadeus#75]
This is a work list for v1 (CRAN or ROpenSci submission, whatever is first). Here I make a quick to-do list for refactoring `process_*` and `calc_*` functions in `amadeus`.

- [x] Reduce the number of function calls that read data from storage (e.g., `terra::rast()`, `terra::vect()`, `terra::time()` etc.) by assigning the output of repetitively used functions once earlier then use the object later multiple times
- [ ] Unifying output class of `calc_*`, plain `data.frame` or `data.table` or `tibble`
    - [ ] Data layout: long or wide data frame?
- [ ] (Discussion point) Human-readable field names versus field codes based on a naming convention as used in `beethoven`

**Comment by mitchellmanware** [comment]
@sigmafelix 

I can work on point 2 (unifying output class of `calc_` functions) while updating for the `geom = ` parameter.

**Comment by sigmafelix** [comment]
@mitchellmanware Thank you for your help. Please let me know when the update is finished. I will merge your branch into mine before making a PR.

**Comment by kyle-messier** [comment]
@mitchellmanware Are you interested in submitting this to ROpenSci? @sigmafelix and I discussed this. He did for `chopin` and it has been a positive experience thus far. I don't think it would impact the EM&S journal submission but may be worth checking

**Comment by kyle-messier** [comment]
Sorry didn't mean to close

**Comment by mitchellmanware** [comment]
If @sigmafelix has found it valuable then I am sure it will be useful for `amadeus` as well. I am not very familiar with ROpenSci but I'll do some reading on it.

**Comment by sigmafelix** [comment]
@kyle-messier @mitchellmanware We can consider ROpenSci after publishing `amadeus` on CRAN. One good aspect of submitting a package to ROpenSci is that it will increase visibility to the larger audience (they post a monthly newsletter that is also posted in R communities). ROpenSci has a little stricter requirements on function examples (they recommend to add examples in all functions), which we need to be aware of. I suggest targeting CRAN first, then discuss ROpenSci later.

**Comment by kyle-messier** [comment]
@sigmafelix @mitchellmanware I am thinking we should submit the publication EM&S first as well, then in pararllel can submit to ROpenSci. Given we want this manuscript to be published or at at least submitted by the time we submit the beethoven manuscript.

**Comment by mitchellmanware** [comment]
So CRAN first, then written version to EM&S, and ROpenSci after those? That seems like a logical progression to me.

@kyle-messier @sigmafelix

**Comment by sigmafelix** [comment]
@kyle-messier @mitchellmanware Agreed on the progression. Let's submit `amadeus` as soon as v.0.2.0 (I think we can call CRAN-ready version as v.1.0.0, what do you think?) is ready.

**Comment by mitchellmanware** [comment]
I think it sounds great. Thanks Insang!
