### ISSUE TITLE
Coverage improvement

### ISSUE THREAD

**Issue by sigmafelix** [NIEHS/amadeus#84]
The current PR's coverage is 97.86%. I couldn't figure out which tests exactly made the PR tests fail now, but soon I will start work on coverage while I am looking into the tests with problems.

<img width="802" alt="image" src="https://github.com/NIEHS/amadeus/assets/25448786/26217c4d-df84-41bd-b31c-3d91416a9158">

**Comment by sigmafelix** [comment]
The current PR coverage is 99.48%. I am closing this issue.

**Comment by kyle-messier** [comment]
🚀 🌔
