### ISSUE TITLE
Add examples in all core user-facing functions

### ISSUE THREAD

**Issue by sigmafelix** [NIEHS/amadeus#85]
A very few functions have examples. We need to add examples to `download_*`, `process_*`, and `calc_*` functions.

**Comment by mitchellmanware** [comment]
https://github.com/NIEHS/amadeus/commit/a7fef09cb3402fb9a92999c485e7fd4cc884d20a

**Comment by mitchellmanware** [comment]
https://github.com/NIEHS/amadeus/commit/67128cf666177f113814be452facbceba6bb0475 for modis functions
