### ISSUE TITLE
`download_*` optional parameters

### ISSUE THREAD

**Issue by mitchellmanware** [NIEHS/amadeus#95]
- [x] `date_start` & `date_end` -> `date = c()`
- [x] `year_start` & `year_end` -> `year = c()`

**Comment by mitchellmanware** [comment]
https://github.com/NIEHS/amadeus/commit/3e28b35226d318f9fdcc1fdea7299d2ec327b3a3

**Comment by mitchellmanware** [comment]
Given the progression of `beethoven` and the manuscript in review, should we wait to adopt new parameter names (ie. "collection", "parameter", "variables" etc all taking the same parameter name) and altered parameter names (ie. "data_format" -> "format') for Version 1.0.1? I have changed temporal paramters so that "year" and "date" now use two character vector instead of "year/date_start" and "year/date_end", but these are reflected in the manuscript.

I want to ensure we have consistent parameter names but also do not want to stall beethoven pipeline development further.
@sigmafelix @kyle-messier

**Comment by sigmafelix** [comment]
@mitchellmanware Thank you for the updates. I think the earlier update is better to stabilize the pipeline. 

To note, character(2) vector part is reflected on the recent `beethoven` update and I am trying to refactor `beethoven` functions to match the recent `amadeus` version.

**Comment by mitchellmanware** [comment]
in that case I will close and leave for a future issue.

Note in the refactored version of `download_gridmet`, the `years <- seq(year[1], year[1], 1)` line has an issue with the indexed year. Should be `years <- seq(year[1], year[2], 1)`.

This change was addressed in https://github.com/NIEHS/amadeus/commit/fcd6cd42cdf81008b735614d812f1a223276965a, but may not be in your most recent pull from mm-manuscript-0627. @sigmafelix
