### ISSUE TITLE
update option names for "mode" variable in process_aqs.R

### ISSUE THREAD

**Issue by MAKassien** [NIEHS/amadeus#98]
Opening this issue after a short discussion with @sigmafelix 

current options for input in `mode` are:

- `"full" `(all dates * all locations)
- `"sparse"` (date-location pairs with available data) or
- ` "location"` (unique locations)

I propose changing the first two names to something more self-explanatory, since I already had some confusion thinking `full` would include dates and locations. One proposed option could be:

- `"date-location" `(all dates * all locations)
- `"available-data"` (date-location pairs with available data) or
- `"location"` (unique locations)

Feel free to propose other names, this is what came to mind on a first pass. I don't know if the hyphens are good practice, we could do away with them too.

**Comment by sigmafelix** [comment]
472e587 reflected the suggestions. Thank you for the comments!
